import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';

import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1>Next Js pre-rendering</h1>
        <ul>
          <li>
            <Link href={'/users'}>Users (getStaticProp)</Link>
          </li>
          <li>
            <Link href={'/posts'}>Posts (getStaticPath)</Link>
          </li>
          <li>
            <Link href={'/products'}>Products (Incremental Static Generation)</Link>
          </li>
          <li>
            <Link href={'/news'}>News (getServerSideProps)</Link>
          </li>
          <li>
            <Link href={'/news/sports'}>News (getServerSideProps with dynamic route- /sports, /politics)</Link>
          </li>
          <li>
            <Link href={'/dashboard'}>Dashboard (Client side data fetching using swr)</Link>
          </li>
          <li>
            <Link href={'/comments'}>API (Create, Read, Delete)</Link>
          </li>
        </ul>
      </main>
    </>
  );
}
