import './globals.css';
import './layout.css';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const HeaderStyle = {
    width: '100%',
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    padding: '2rem 1rem',
    fontSize: '18px',
    fontWeight: 'bold',
  };

  const LinkStyle = {
    padding: '5px 10px',
  };
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div style={HeaderStyle}>
            <Link style={LinkStyle} href="/">Home</Link>
            <Link style={LinkStyle} href="/login">Login </Link>
            <Link style={LinkStyle} href="/login/about-login">login/about-login</Link>
            <Link style={LinkStyle} href="/about">(marketing)about</Link>
            <Link style={LinkStyle} href="/blog">(marketing)blog</Link>
            <Link style={LinkStyle} href="/products">Products</Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
